name: Build Releases
on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-musl

          - os-name: Linux-armv7
            runs-on: ubuntu-latest
            target: armv7-unknown-linux-musleabihf

          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc


    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Package artifacts
        shell: bash
        run: |
          STAGING="omni-ping-${{ matrix.platform.target }}"
          mkdir -p "$STAGING"

          if [[ "${{ matrix.platform.target }}" == *"-windows-"* ]]; then
            cp "target/${{ matrix.platform.target }}/release/client.exe" "$STAGING/"
            cp "target/${{ matrix.platform.target }}/release/server.exe" "$STAGING/"
            7z a "$STAGING.zip" "$STAGING"
            echo "ASSET=$STAGING.zip" >> $GITHUB_ENV
          else
            cp "target/${{ matrix.platform.target }}/release/client" "$STAGING/"
            cp "target/${{ matrix.platform.target }}/release/server" "$STAGING/"
            tar czf "$STAGING.tar.gz" "$STAGING"
            echo "ASSET=$STAGING.tar.gz" >> $GITHUB_ENV
          fi

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, "refs/tags/")
        with:
          files: ${{ env.ASSET }}
          generate_release_notes: true
